[development]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
#secret_key = "W1l0fG17Sk1Xek4oSG5yMSJsNQ=="
limits = { forms = 32768 }
template_dir = "src/templates/"

[staging]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
#secret_key = "W1l0fG17Sk1Xek4oSG5yMSJsNQ=="
limits = { forms = 32768 }
template_dir = "src/templates/"

[production]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
#secret_key = "W1l0fG17Sk1Xek4oSG5yMSJsNQ=="
limits = { forms = 32768 }
template_dir = "src/templates/"
